server:
  port: 8084
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        #bootstrap: true
        git:
          strict-host-key-checking: false
          username: shreedharcb148
          password:  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
          clone-on-start: true
          #uri: https://github.com/shreedharcb148/microservices-config
          uri : file:///C:/Users/WLH1KOR/Desktop/SpringWorkspace/SpringBootLearningProjects/microserviceworkspace/git-localconfig-repo
           
         
    