server:
  port: 8084
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        bootstrap: true
        git:
          #uri: https://github.com/shreedharcb148/microservices-config
          #clone-on-start: true
          strict-host-key-checking: false
          username: shreedharcb148
          password:  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
          #uri : file:///C:/Users/WLH1KOR/Desktop/SpringWorkspace/SpringBootLearningProjects/microserviceworkspace/durgesh-microservices-learning/microservices-config
           #actuators configuration

    

    